# Generated by Django 3.0.7 on 2020-08-02 13:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_flight_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='numOfPassengers',
            new_name='userId',
        ),
        migrations.AddField(
            model_name='flight',
            name='capacity',
            field=models.IntegerField(default=200),
        ),
        migrations.AddField(
            model_name='flight',
            name='numOfPassengers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='passenger',
            name='address',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='passenger',
            name='dateOfBirth',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='passenger',
            name='flights',
            field=models.ManyToManyField(to='booking.Flight'),
        ),
        migrations.AddField(
            model_name='trip',
            name='passengers',
            field=models.ManyToManyField(to='booking.Passenger'),
        ),
    ]
