# Generated by Django 3.0.7 on 2020-08-03 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_auto_20200803_1455'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passenger',
            name='address',
        ),
    ]
