# Generated by Django 2.2.12 on 2020-08-04 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_remove_passenger_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='destination',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trip',
            name='flights',
            field=models.ManyToManyField(to='booking.Flight'),
        ),
        migrations.AddField(
            model_name='trip',
            name='origin',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
    ]
