# Generated by Django 2.2.12 on 2020-08-04 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_auto_20200804_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='totalAmound',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
