# Generated by Django 2.2.12 on 2020-08-04 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_trip_totalamound'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='totalAmound',
            new_name='totalAmount',
        ),
    ]
