# Generated by Django 3.0.7 on 2020-08-05 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0011_auto_20200804_2347'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='image',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
