# Generated by Django 3.0.7 on 2020-08-05 03:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0013_auto_20200805_0236'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelbooking',
            name='checkIn',
            field=models.DateField(default=datetime.datetime(2020, 8, 5, 3, 35, 29, 211720)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hotelbooking',
            name='checkOut',
            field=models.DateField(default=datetime.datetime(2020, 8, 5, 3, 35, 40, 48187)),
            preserve_default=False,
        ),
    ]
